[package]
name = "dl"
version = "0.0.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/IvanUkhov/dl"
homepage = "https://github.com/IvanUkhov/dl"
description = "DL."
